# Generated by Django 5.2 on 2026-06-13 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_unit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
